// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxX4ucFHMn_rV12XE35dDYaFD6XmqFLDo',
    appId: '1:561079665625:web:c083aa655f3e7aee250fc8',
    messagingSenderId: '561079665625',
    projectId: 'inkspire-7f5e6',
    authDomain: 'inkspire-7f5e6.firebaseapp.com',
    storageBucket: 'inkspire-7f5e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1e0eVt80HmgC7FgmVFoxv55t3vlcxeAc',
    appId: '1:561079665625:android:ee8f84c54d19ed8e250fc8',
    messagingSenderId: '561079665625',
    projectId: 'inkspire-7f5e6',
    storageBucket: 'inkspire-7f5e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvY2c694GHMC6giWyIGsRww6td_doUmH4',
    appId: '1:561079665625:ios:1aa41468c1078f71250fc8',
    messagingSenderId: '561079665625',
    projectId: 'inkspire-7f5e6',
    storageBucket: 'inkspire-7f5e6.firebasestorage.app',
    iosBundleId: 'com.example.inkspire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvY2c694GHMC6giWyIGsRww6td_doUmH4',
    appId: '1:561079665625:ios:1aa41468c1078f71250fc8',
    messagingSenderId: '561079665625',
    projectId: 'inkspire-7f5e6',
    storageBucket: 'inkspire-7f5e6.firebasestorage.app',
    iosBundleId: 'com.example.inkspire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxX4ucFHMn_rV12XE35dDYaFD6XmqFLDo',
    appId: '1:561079665625:web:58ea609f9dcf6a9e250fc8',
    messagingSenderId: '561079665625',
    projectId: 'inkspire-7f5e6',
    authDomain: 'inkspire-7f5e6.firebaseapp.com',
    storageBucket: 'inkspire-7f5e6.firebasestorage.app',
  );
}
